# Generated by Django 3.2.16 on 2022-11-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testforuser', '0002_auto_20221111_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категорию теста', 'verbose_name_plural': 'категории тестов'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['title'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testforuser.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.FloatField(verbose_name='сложность'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='test',
            name='timer',
            field=models.PositiveSmallIntegerField(verbose_name='время на решение теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=300, verbose_name='название теста'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Вопрос')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testforuser.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Ответ')),
                ('right_false', models.BooleanField(verbose_name='Верный или отрицательный ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testforuser.question', verbose_name='Вопрос')),
            ],
        ),
    ]
