# Generated by Django 3.2.16 on 2022-11-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testforuser', '0003_auto_20221115_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question_id'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test_id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
