# Generated by Django 3.2.16 on 2022-12-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testforuser', '0005_auto_20221213_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='many_category',
            new_name='category',
        ),
    ]
