# Generated by Django 3.2.16 on 2022-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testforuser', '0007_remove_kit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('Синий', 'text-bg-primary'), ('Серый', 'text-bg-secondary'), ('Зеленный', 'text-bg-success'), ('Красный', 'text-bg-danger'), ('Жёлтый', 'text-bg-warning'), ('Голубой', 'text-bg-info'), ('Белый', 'text-bg-light'), ('Чёрный', 'text-bg-dark')], max_length=100, null=True),
        ),
    ]
