# Generated by Django 3.2.16 on 2022-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testforuser', '0008_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('text-bg-primary', 'Синий'), ('text-bg-secondary', 'Серый'), ('text-bg-success', 'Зеленный'), ('text-bg-danger', 'Красный'), ('text-bg-warning', 'Жёлтый'), ('text-bg-info', 'Голубой'), ('text-bg-light', 'Белый'), ('text-bg-dark', 'Чёрный')], max_length=100, null=True),
        ),
    ]
